# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16MnzEVKg1_9tEXjmmM9fUrB6Vpf5lE2M
"""



"""Unit2_L2
1. What is Python and why is it useful?
        

   Python is a high level programming language. Python is used for AI,   maching learning, operating system etc.

2. Are the following variable names allowed in python?
1_message - not allowed,
Greeting_message - allowed,
Message_1 - allowed,
First name - not allowed,
Full_name - allowed,
"""

var = "Hello There!"
print(var)

first_name = "umme"
last_name = "habiba"
email_extension = "@gmail.com"
print(first_name+last_name+email_extension)

name = "Umme"
print(name.lower())
print(name.upper())

date = 15
var = "Do you want to hang out on the " + str(date) +"th of this month?"
print(var)

#Unit2_L3
list = ["sister sister", "how I met your mother", "the good doctor", "the originals", "agents of shield"]
print(list)
list.sort()
print(list)
list.sort(reverse=True)
print(list)
len(list)

#Unit2_L4
#Create a list that holds 5 data variables.
My_list = ["sister sister", "how I met your mother", "the good doctor", "the originals", "agents of shield"]
#Print out those variables by using a for loop.
for i in My_list:
  print(i)

#Modify your for loop to add a message to your for loop.
for i in My_list:
  print(i.title() + " is one of my favorite tv shows")

#Use a for loop to print even numbers from 1-20.
num = 20
for i in range(1,21):
    if i % 2 == 0:     
      print(i, end =' ')

#Sort your list in alphabetic order.
list = ["sister sister", "how I met your mother", "the good doctor", "the originals", "agents of shield"]
list.sort()
print(list)

#Print out the first three elements of your list.
print(list[0:3])

#Print out the last two elements of your list.
print(list[3:5])

#Lesson 5: If-elif-else Statements 
user_name = ['umme', 'admin', 'bill', 'joe', 'kate']

for username in user_name:
    if username == 'admin':
        print("Hello admin, welcome back! what would you like to see today?")
    else:
        print("Hello " + username + ", welcome to our login page")

numbers = [1,2,3,4,5,6,7,8,9,10]

for number in numbers:
    if number == 1:
        print("1st")
    elif number == 2:
        print("2nd")
    elif number == 3:
        print("3rd")
    else:
        print(str(number)+ "th")

#Lesson:6 Unit 2 – Python Dictionaries 
name = {'first_name': 'Jhon','last_name': 'Doe'}
#Print out those variables stored in your previous dictionary. 
print(name['first_name'] + " " + name['last_name'])
#Add a message to those variables on printing: for example: “Hello, firstname lastname!”
print("Hello, " + name['first_name'] + " " + name['last_name'])

#Create a dictionary that holds 2 key: value pairs:
dic = {'name': 'Habiba', 'age': '21'}
print(dic['name'])
print(dic['age'])

#Create a nested dictionary containing three dictionaries
dic = {'favorite pets': 'cat', 'travel locations': 'italy', 'favorite food': 'chocolate'}
for i in dic:
  print(dic[i])

#Python Project – Odd or Even
num = int(input("Enter a number: "))
check = int(input("Enter a number: "))

if num % 2 == 0:
     print(num, "is an even number")
else:
    print(num, "is an odd number")  
if num % 4 == 0:
     print(num, "is a multiple of 4")
if num % check == 0:
    print(num, "divides evenly")
else:
    print(num, "does not divide evenly, try again!")

#Python Project
import random
Rock = '1'
Paper = '2'
Scissors = '3'
player=int(input('Please enter number 1 = Rock, 2 = Paper, 3 = Scissors: '))
if player<1 or player>3:
   player=int(input('Invalid number. please try again'))
else:
   player2=random.randint(1, 3)
   print(player1,player2)
   if player1==1 and player2==1 or player1==2 and computer==2 or player1==3 and computer==3:
       print('It is a draw.')
   if player==1 and player2==2 or player1==2 and player2==3 or player1==3 and player2==1:
       print('player2 wins!')
   if player1==1 and player2==3 or player1==2 and player2==1 or player1==3 and player2==2:
       print('player1 wins!')